### ISSUE TITLE
Writing to Spanner failing after upgrading to Scio 0.5.3 and Beam 2.4.0

### ISSUE THREAD

**Issue by dsquier** [spotify/scio#1138]
## Issue

After upgrading Scio from 0.5.0 -> 0.5.3 and Apache Beam from 2.2.0 -> 2.4.0, a batch Dataflow job is erroring out, unable to complete.

## Test Case

Please see: https://github.com/dsquier/scio-beam-spanner-testcase

This repo contains all information to re-produce this issue. It requires an active GCP account and ability to create a 1-node Spanner instance for testing. All Spanner DDL steps, test data, and code are included.

- Error also occurs with Scio 0.5.1 and 0.5.2.
- Downgrading to Scio 0.5.0 + Beam 2.2.0 solves the problem. The jobs completes without error.

## Error Encountered

```
java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: java.lang.ArrayIndexOutOfBoundsException: 97
	at com.google.cloud.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output(GroupAlsoByWindowsParDoFn.java:183)
	at com.google.cloud.dataflow.worker.GroupAlsoByWindowFnRunner$1.outputWindowedValue(GroupAlsoByWindowFnRunner.java:101)
	at com.google.cloud.dataflow.worker.util.BatchGroupAlsoByWindowViaIteratorsFn.processElement(BatchGroupAlsoByWindowViaIteratorsFn.java:124)
	at com.google.cloud.dataflow.worker.util.BatchGroupAlsoByWindowViaIteratorsFn.processElement(BatchGroupAlsoByWindowViaIteratorsFn.java:53)
	at com.google.cloud.dataflow.worker.GroupAlsoByWindowFnRunner.invokeProcessElement(GroupAlsoByWindowFnRunner.java:114)
	at com.google.cloud.dataflow.worker.GroupAlsoByWindowFnRunner.processElement(GroupAlsoByWindowFnRunner.java:72)
	at com.google.cloud.dataflow.worker.GroupAlsoByWindowsParDoFn.processElement(GroupAlsoByWindowsParDoFn.java:113)
	at com.google.cloud.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:43)
	at com.google.cloud.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:48)
	at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:200)
	at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:158)
	at com.google.cloud.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:75)
	at com.google.cloud.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:383)
	at com.google.cloud.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:355)
	at com.google.cloud.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:286)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.doWork(DataflowBatchWorkerHarness.java:134)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:114)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:101)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.beam.sdk.util.UserCodeException: java.lang.ArrayIndexOutOfBoundsException: 97
	at org.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:36)
	at org.apache.beam.sdk.io.gcp.spanner.SpannerIO$BatchFn$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:177)
	at org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:138)
	at com.google.cloud.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:323)
	at com.google.cloud.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:43)
	at com.google.cloud.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:48)
	at com.google.cloud.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output(GroupAlsoByWindowsParDoFn.java:181)
	... 21 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 97
	at org.apache.beam.sdk.io.gcp.spanner.MutationGroupEncoder.decodeMutation(MutationGroupEncoder.java:276)
	at org.apache.beam.sdk.io.gcp.spanner.MutationGroupEncoder.decode(MutationGroupEncoder.java:267)
	at org.apache.beam.sdk.io.gcp.spanner.SpannerIO$BatchFn.processElement(SpannerIO.java:944)```

**Comment by dsquier** [comment]
I can confirm this also happens with Scio 0.5.3. I updated the testcase repo to reflect this.

**Comment by nevillelyh** [comment]
Possibly related to #1136 and fixed in #1140

**Comment by nevillelyh** [comment]
@dsquier I published a `0.5.4-PR1140-SNAPSHOT` with the fix. Can you give it a try?
https://github.com/spotify/scio/wiki/FAQ#how-do-i-use-the-snapshot-builds-of-scio

**Comment by dsquier** [comment]
I updated to `0.5.4-PR1140-SNAPSHOT` and re-tested. Unfortunately, the error is still occurring.

Also, just for posterity:

## Dependencies.scala

```
import sbt._

object Dependencies {
  val scioVersion = "0.5.4-PR1140-SNAPSHOT"
  val beamVersion = "2.4.0"
  val defaultScalaVersion = "2.12.5"
  val scalaMacrosVersion = "2.1.1"
  val circeVersion = "0.9.2"
  val slf4jVersion = "1.7.25"

  lazy val commonDependencies = Seq(
    "com.spotify" %% "scio-core" % scioVersion,
    "com.spotify" %% "scio-test" % scioVersion % "test",
    "org.apache.beam" % "beam-runners-direct-java" % beamVersion,
    "org.apache.beam" % "beam-runners-google-cloud-dataflow-java" % beamVersion,
    "org.slf4j" % "slf4j-simple" % slf4jVersion,
    "io.circe" %% "circe-core" % circeVersion,
    "io.circe" %% "circe-generic" % circeVersion,
    "io.circe" %% "circe-parser" % circeVersion
  )

  lazy val paradiseDependency = "org.scalamacros" % "paradise" % scalaMacrosVersion cross CrossVersion.full

  lazy val macroDependencies = "org.scala-lang" % "scala-reflect" % defaultScalaVersion
}
```

## SBT log

```
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from C:\Users\dsquier\.sbt\1.0\plugins
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from C:\Users\dsquier\GitHub\scio-beam-spanner-testcase\project
[info] Loading settings from build.sbt ...
[info] Set current project to droplistMigration (in build file:/C:/Users/dsquier/GitHub/scio-beam-spanner-testcase/)
[info] Updating ...
[warn] Choosing sonatype-snapshots for com.spotify#scio-core_2.12;0.5.4-PR1140-SNAPSHOT
[warn] Choosing sonatype-snapshots for com.spotify#scio-avro_2.12;0.5.4-PR1140-SNAPSHOT
[warn] Choosing sonatype-snapshots for com.spotify#scio-bigquery_2.12;0.5.4-PR1140-SNAPSHOT
[warn] Choosing sonatype-snapshots for com.spotify#scio-test_2.12;0.5.4-PR1140-SNAPSHOT
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/com/spotify/scio-core_2.12/0.5.4-PR1140-SNAPSHOT/scio-core_2.12-0.5.4-PR1140-SNAPSHOT.jar ...
[info]  [SUCCESSFUL ] com.spotify#scio-core_2.12;0.5.4-PR1140-SNAPSHOT!scio-core_2.12.jar (3043ms)
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/com/spotify/scio-avro_2.12/0.5.4-PR1140-SNAPSHOT/scio-avro_2.12-0.5.4-PR1140-SNAPSHOT.jar ...
[info]  [SUCCESSFUL ] com.spotify#scio-avro_2.12;0.5.4-PR1140-SNAPSHOT!scio-avro_2.12.jar (2463ms)
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/com/spotify/scio-bigquery_2.12/0.5.4-PR1140-SNAPSHOT/scio-bigquery_2.12-0.5.4-PR1140-SNAPSHOT.jar ...
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/com/spotify/scio-test_2.12/0.5.4-PR1140-SNAPSHOT/scio-test_2.12-0.5.4-PR1140-SNAPSHOT.jar ...
[info]  [SUCCESSFUL ] com.spotify#scio-bigquery_2.12;0.5.4-PR1140-SNAPSHOT!scio-bigquery_2.12.jar (2004ms)
[info]  [SUCCESSFUL ] com.spotify#scio-test_2.12;0.5.4-PR1140-SNAPSHOT!scio-test_2.12.jar (723ms)
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]  * org.typelevel:cats-kernel_2.12:1.0.1 is selected over 0.9.0
[warn]      +- org.typelevel:cats-core_2.12:1.0.1 ()              (depends on 1.0.1)
[warn]      +- org.typelevel:algebra_2.12:0.7.0 ()                (depends on 0.9.0)
[warn]  * com.google.api.grpc:proto-google-cloud-spanner-admin-database-v1:0.1.9 is selected over 0.1.11
[warn]      +- com.google.cloud:google-cloud-spanner:0.20.0b-beta (depends on 0.1.11)
[warn]      +- com.google.api.grpc:grpc-google-cloud-spanner-admin-database-v1:0.1.11 (depends on 0.1.11)
[warn]      +- org.apache.beam:beam-sdks-java-io-google-cloud-platform:2.4.0 (depends on 0.1.11)
[warn]  * com.google.guava:guava:20.0 is selected over {18.0, 19.0}
[warn]      +- com.spotify:scio-core_2.12:0.5.4-PR1140-SNAPSHOT   (depends on 20.0)
[warn]      +- org.apache.beam:beam-sdks-java-io-google-cloud-platform:2.4.0 (depends on 20.0)
[warn]      +- com.google.auth:google-auth-library-appengine:0.7.0 (depends on 19.0)
[warn]      +- com.google.cloud.bigtable:bigtable-protos:1.0.0-pre3 (depends on 19.0)
[warn]      +- com.google.cloud.bigtable:bigtable-client-core:1.0.0 (depends on 19.0)
[warn]      +- com.google.cloud:google-cloud-core:1.0.2           (depends on 19.0)
[warn]      +- io.grpc:grpc-protobuf-nano:1.2.0                   (depends on 19.0)
[warn]      +- io.opencensus:opencensus-api:0.7.0                 (depends on 19.0)
[warn]      +- com.google.auto.service:auto-service:1.0-rc3       (depends on 19.0)
[warn]      +- com.google.protobuf:protobuf-java-util:3.2.0       (depends on 18.0)
[warn]      +- com.google.auth:google-auth-library-oauth2-http:0.7.1 (depends on 18.0)
[warn]      +- com.google.cloud.bigdataoss:gcsio:1.4.5            (depends on 18.0)
[warn]      +- io.grpc:grpc-protobuf:1.6.1                        (depends on 18.0)
[warn]      +- com.google.cloud:google-cloud-core-grpc:1.2.0      (depends on 18.0)
[warn]      +- io.grpc:grpc-protobuf:1.2.0                        (depends on 18.0)
[warn]      +- io.grpc:grpc-core:1.2.0                            (depends on 18.0)
[warn]      +- com.google.protobuf:protobuf-java-util:3.3.1       (depends on 18.0)
[warn]      +- io.grpc:grpc-protobuf-lite:1.6.1                   (depends on 18.0)
[warn]      +- com.google.auto:auto-common:0.3                    (depends on 18.0)
[warn]      +- com.google.api:api-common:1.1.0                    (depends on 18.0)
[warn]      +- com.google.api:gax:1.3.1                           (depends on 18.0)
[warn]      +- com.google.cloud.datastore:datastore-v1-proto-client:1.4.0 (depends on 18.0)
[warn]      +- io.grpc:grpc-protobuf-lite:1.2.0                   (depends on 18.0)
[warn]      +- com.google.api:gax-grpc:0.20.0                     (depends on 18.0)
[warn]      +- io.grpc:grpc-protobuf-nano:1.0.1                   (depends on 18.0)
[warn]      +- com.google.cloud.bigdataoss:util:1.4.5             (depends on 18.0)
[warn]  * io.netty:netty-tcnative-boringssl-static:2.0.6.Final is selected over 1.1.33.Fork26
[warn]      +- com.google.cloud.bigtable:bigtable-client-core:1.0.0 (depends on 1.1.33.Fork26)
[warn]      +- com.google.cloud:google-cloud-spanner:0.20.0b-beta (depends on 1.1.33.Fork26)
[warn]      +- org.apache.beam:beam-sdks-java-io-google-cloud-platform:2.4.0 (depends on 1.1.33.Fork26)
[warn]  * com.google.cloud.bigtable:bigtable-protos:1.0.0-pre3 is selected over 1.0.0
[warn]      +- org.apache.beam:beam-sdks-java-io-google-cloud-platform:2.4.0 (depends on 1.0.0-pre3)
[warn]      +- com.google.cloud.bigtable:bigtable-client-core:1.0.0 (depends on 1.0.0)
[warn]  * com.google.api.grpc:grpc-google-common-protos:0.1.9 is selected over 0.1.0
[warn]      +- com.google.cloud.datastore:datastore-v1-protos:1.3.0 (depends on 0.1.0)
[warn]      +- com.google.cloud.bigtable:bigtable-protos:1.0.0-pre3 (depends on 0.1.0)
[warn]  * com.google.api.grpc:proto-google-iam-v1:0.1.18 is selected over {0.1.11, 0.1.9}
[warn]      +- com.google.api.grpc:proto-google-cloud-pubsub-v1:0.1.18 (depends on 0.1.11)
[warn]      +- com.google.cloud:google-cloud-core:1.0.2           (depends on 0.1.11)
[warn]      +- com.google.api.grpc:proto-google-cloud-spanner-admin-instance-v1:0.1.11 (depends on 0.1.11)
[warn]      +- com.google.api.grpc:proto-google-cloud-spanner-admin-database-v1:0.1.9 (depends on 0.1.11)
[warn]  * com.google.api.grpc:proto-google-common-protos:0.1.9 is selected over {0.1.18, 0.1.11}
[warn]      +- com.google.api.grpc:grpc-google-common-protos:0.1.9 (depends on 0.1.11)
[warn]      +- com.google.cloud:google-cloud-core:1.0.2           (depends on 0.1.11)
[warn]      +- com.google.api.grpc:proto-google-cloud-spanner-v1:0.1.11b (depends on 0.1.11)
[warn]      +- com.google.api:gax-grpc:0.20.0                     (depends on 0.1.11)
[warn]      +- io.grpc:grpc-protobuf:1.6.1                        (depends on 0.1.11)
[warn]      +- com.google.api.grpc:proto-google-longrunning-v1:0.1.11 (depends on 0.1.11)
[warn]      +- com.google.api.grpc:proto-google-cloud-spanner-admin-instance-v1:0.1.11 (depends on 0.1.11)
[warn]      +- com.google.api.grpc:proto-google-cloud-spanner-admin-database-v1:0.1.9 (depends on 0.1.11)
[warn]      +- org.apache.beam:beam-sdks-java-io-google-cloud-platform:2.4.0 (depends on 0.1.11)
[warn]      +- com.google.api.grpc:proto-google-cloud-pubsub-v1:0.1.18 (depends on 0.1.18)
[warn]      +- com.google.api.grpc:proto-google-iam-v1:0.1.18     (depends on 0.1.18)
[warn]  * com.google.protobuf:protobuf-java:3.3.1 is selected over {3.4.0, 2.4.1, 3.0.0, 3.3.0, 3.2.0}
[warn]      +- com.google.cloud.bigtable:bigtable-protos:1.0.0-pre3 (depends on 3.3.1)
[warn]      +- com.google.protobuf:protobuf-java-util:3.3.1       (depends on 3.3.1)
[warn]      +- com.spotify:scio-core_2.12:0.5.4-PR1140-SNAPSHOT   (depends on 3.2.0)
[warn]      +- com.google.protobuf:protobuf-java-util:3.2.0       (depends on 3.2.0)
[warn]      +- com.google.api.grpc:proto-google-cloud-spanner-v1:0.1.11b (depends on 3.2.0)
[warn]      +- org.apache.beam:beam-sdks-java-extensions-protobuf:2.4.0 (depends on 3.2.0)
[warn]      +- io.grpc:grpc-protobuf:1.6.1                        (depends on 3.2.0)
[warn]      +- com.google.cloud:google-cloud-core-grpc:1.2.0      (depends on 3.2.0)
[warn]      +- com.google.api.grpc:proto-google-cloud-spanner-admin-database-v1:0.1.9 (depends on 3.2.0)
[warn]      +- io.grpc:grpc-protobuf:1.2.0                        (depends on 3.2.0)
[warn]      +- com.google.api.grpc:proto-google-longrunning-v1:0.1.11 (depends on 3.2.0)
[warn]      +- com.google.api.grpc:proto-google-cloud-spanner-admin-instance-v1:0.1.11 (depends on 3.2.0)
[warn]      +- com.google.api.grpc:proto-google-common-protos:0.1.9 (depends on 3.2.0)
[warn]      +- org.apache.beam:beam-sdks-java-io-google-cloud-platform:2.4.0 (depends on 3.2.0)
[warn]      +- com.google.api.grpc:proto-google-cloud-pubsub-v1:0.1.18 (depends on 3.3.0)
[warn]      +- com.google.api.grpc:proto-google-iam-v1:0.1.18     (depends on 3.3.0)
[warn]      +- com.google.cloud.datastore:datastore-v1-protos:1.3.0 (depends on 2.4.1)
[warn]      +- com.google.api.grpc:grpc-google-common-protos:0.1.0 (depends on 2.4.1)
[warn]      +- com.google.http-client:google-http-client-protobuf:1.20.0 (depends on 2.4.1)
[warn]      +- com.google.cloud.bigtable:bigtable-client-core:1.0.0 (depends on 3.4.0)
[warn]  * com.google.apis:google-api-services-storage:v1-rev71-1.22.0 is selected over v1-rev35-1.20.0
[warn]      +- org.apache.beam:beam-runners-google-cloud-dataflow-java:2.4.0 (depends on v1-rev71-1.22.0)
[warn]      +- org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core:2.4.0 (depends on v1-rev35-1.20.0)
[warn]      +- com.google.cloud.bigdataoss:gcsio:1.4.5            (depends on v1-rev35-1.20.0)
[warn]      +- com.google.cloud.bigdataoss:util:1.4.5             (depends on v1-rev35-1.20.0)
[warn]  * com.google.auth:google-auth-library-oauth2-http:0.7.1 is selected over 0.7.0
[warn]      +- org.apache.beam:beam-runners-google-cloud-dataflow-java:2.4.0 (depends on 0.7.1)
[warn]      +- org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core:2.4.0 (depends on 0.7.1)
[warn]      +- org.apache.beam:beam-sdks-java-io-google-cloud-platform:2.4.0 (depends on 0.7.1)
[warn]      +- com.google.auth:google-auth-library-appengine:0.7.0 (depends on 0.7.0)
[warn]      +- com.google.cloud.bigtable:bigtable-client-core:1.0.0 (depends on 0.7.0)
[warn]      +- com.google.api:gax:1.3.1                           (depends on 0.7.0)
[warn]      +- com.google.api:gax-grpc:0.20.0                     (depends on 0.7.0)
[warn]  * com.google.auth:google-auth-library-credentials:0.7.1 is selected over {0.7.0, 0.4.0}
[warn]      +- org.apache.beam:beam-runners-google-cloud-dataflow-java:2.4.0 (depends on 0.7.1)
[warn]      +- org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core:2.4.0 (depends on 0.7.1)
[warn]      +- com.google.auth:google-auth-library-oauth2-http:0.7.1 (depends on 0.7.1)
[warn]      +- org.apache.beam:beam-sdks-java-io-google-cloud-platform:2.4.0 (depends on 0.7.1)
[warn]      +- com.google.auth:google-auth-library-appengine:0.7.0 (depends on 0.7.0)
[warn]      +- com.google.cloud.bigtable:bigtable-client-core:1.0.0 (depends on 0.7.0)
[warn]      +- com.google.api:gax-grpc:0.20.0                     (depends on 0.7.0)
[warn]      +- io.grpc:grpc-auth:1.2.0                            (depends on 0.7.0)
[warn]  * com.google.code.findbugs:jsr305:3.0.1 is selected over {3.0.2, 3.0.0, 2.0.3, 1.3.9}
[warn]      +- org.apache.beam:beam-runners-google-cloud-dataflow-java:2.4.0 (depends on 3.0.1)
[warn]      +- org.apache.beam:beam-runners-local-java-core:2.4.0 (depends on 3.0.1)
[warn]      +- io.opencensus:opencensus-api:0.7.0                 (depends on 3.0.1)
[warn]      +- org.apache.beam:beam-sdks-java-core:2.4.0          (depends on 3.0.2)
[warn]      +- com.google.cloud.bigtable:bigtable-protos:1.0.0-pre3 (depends on 3.0.2)
[warn]      +- com.google.cloud.bigtable:bigtable-client-core:1.0.0 (depends on 3.0.2)
[warn]      +- com.google.cloud:google-cloud-spanner:0.20.0b-beta (depends on 3.0.2)
[warn]      +- com.google.instrumentation:instrumentation-api:0.3.0 (depends on 3.0.2)
[warn]      +- com.google.cloud.bigdataoss:gcsio:1.4.5            (depends on 3.0.2)
[warn]      +- com.google.oauth-client:google-oauth-client:1.22.0 (depends on 3.0.2)
[warn]      +- io.grpc:grpc-core:1.2.0                            (depends on 3.0.2)
[warn]      +- com.google.http-client:google-http-client:1.22.0   (depends on 3.0.2)
[warn]      +- org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core:2.4.0 (depends on 3.0.2)
[warn]      +- com.google.api:api-common:1.1.0                    (depends on 3.0.2)
[warn]      +- com.google.api:gax:1.3.1                           (depends on 3.0.2)
[warn]      +- com.google.api:gax-grpc:0.20.0                     (depends on 3.0.2)
[warn]      +- io.opencensus:opencensus-contrib-grpc-util:0.7.0   (depends on 3.0.2)
[warn]      +- org.apache.beam:beam-sdks-java-io-google-cloud-platform:2.4.0 (depends on 3.0.2)
[warn]      +- com.google.cloud.bigdataoss:util:1.4.5             (depends on 3.0.2)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 1 Scala source to C:\Users\dsquier\GitHub\scio-beam-spanner-testcase\target\scala-2.12\classes ...
```
## Error

```
java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: java.lang.ArrayIndexOutOfBoundsException: 56
	at com.google.cloud.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output(GroupAlsoByWindowsParDoFn.java:183)
	at com.google.cloud.dataflow.worker.GroupAlsoByWindowFnRunner$1.outputWindowedValue(GroupAlsoByWindowFnRunner.java:101)
	at com.google.cloud.dataflow.worker.util.BatchGroupAlsoByWindowViaIteratorsFn.processElement(BatchGroupAlsoByWindowViaIteratorsFn.java:124)
	at com.google.cloud.dataflow.worker.util.BatchGroupAlsoByWindowViaIteratorsFn.processElement(BatchGroupAlsoByWindowViaIteratorsFn.java:53)
	at com.google.cloud.dataflow.worker.GroupAlsoByWindowFnRunner.invokeProcessElement(GroupAlsoByWindowFnRunner.java:114)
	at com.google.cloud.dataflow.worker.GroupAlsoByWindowFnRunner.processElement(GroupAlsoByWindowFnRunner.java:72)
	at com.google.cloud.dataflow.worker.GroupAlsoByWindowsParDoFn.processElement(GroupAlsoByWindowsParDoFn.java:113)
	at com.google.cloud.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:43)
	at com.google.cloud.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:48)
	at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:200)
	at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:158)
	at com.google.cloud.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:75)
	at com.google.cloud.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:383)
	at com.google.cloud.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:355)
	at com.google.cloud.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:286)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.doWork(DataflowBatchWorkerHarness.java:134)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:114)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:101)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.beam.sdk.util.UserCodeException: java.lang.ArrayIndexOutOfBoundsException: 56
	at org.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:36)
	at org.apache.beam.sdk.io.gcp.spanner.SpannerIO$BatchFn$DoFnInvoker.invokeProcessElement(Unknown Source)
	at org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:177)
	at org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:138)
	at com.google.cloud.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:323)
	at com.google.cloud.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:43)
	at com.google.cloud.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:48)
	at com.google.cloud.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output(GroupAlsoByWindowsParDoFn.java:181)
	... 21 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 56
	at org.apache.beam.sdk.io.gcp.spanner.MutationGroupEncoder.decodeMutation(MutationGroupEncoder.java:276)
	at org.apache.beam.sdk.io.gcp.spanner.MutationGroupEncoder.decode(MutationGroupEncoder.java:267)
	at org.apache.beam.sdk.io.gcp.spanner.SpannerIO$BatchFn.processElement(SpannerIO.java:944)
```

**Comment by nevillelyh** [comment]
It's a long shot, but can you try scala `2.11.12` instead?
Also is it possible to reproduce in a unit test or tiny job with `DirectRunner`, ideally without actually needing to write to Spanner?

**Comment by dsquier** [comment]
Sure, I will test Scala `2.12.12`.

My initial attempts to get the job to run via DirectRunner were not successful. I will revisit it and see if I can remove the actual write to Spanner.

**Comment by dsquier** [comment]
Switched to Scala `2.12.12` (only change) and it won't compile due to an error with the Circe JSON library:

```
[error] C:\Users\dsquier\GitHub\scio-beam-spanner-testcase\src\main\scala\com\joinhoney\sciobeamspannertestcase\Testcase.scala:112:70: value getOrElse is not a member of io.circe.Decoder.Result[List[com.joinhoney.sciobeamspannertestcase.Notification]]
```

**Comment by dsquier** [comment]
I tried Scala `2.11.12`. I was unable to get the job to compile due to a `missing type error`, i.e.,

```
[error] C:\Users\dsquier\GitHub\scio-beam-spanner-testcase\src\main\scala\com\joinhoney\sciobeamspannertestcase\Testcase.scala:179:42: missing parameter type
[error]       price_notified_values_list.forEach(item => notifications += getPriceNotified(item.getEntityValue))
```

This doesn't happen with Scala `2.12.5`.

I am working on paring down the test case. Will follow up when ready.

**Comment by nevillelyh** [comment]
https://github.com/dsquier/scio-beam-spanner-testcase/blob/master/src/main/scala/com/joinhoney/sciobeamspannertestcase/Testcase.scala#L178

This is something in your test code and should be fixable?

**Comment by dsquier** [comment]
Fixed issue and pushed to test repo: https://github.com/dsquier/scio-beam-spanner-testcase/commit/dc6c7c95ca5188f7b53f1b2662739536a9055328

Re-ran test and still encountering error:

```
[ForkJoinPool-1-worker-5] ERROR org.apache.beam.runners.dataflow.util.MonitoringUtil$LoggingHandler - 2018-05-09T22:22:14.200Z: java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: java.lang.ArrayIndexOutOfBoundsException: 98
        at com.google.cloud.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output(GroupAlsoByWindowsParDoFn.java:183)
        at com.google.cloud.dataflow.worker.GroupAlsoByWindowFnRunner$1.outputWindowedValue(GroupAlsoByWindowFnRunner.java:101)
        at com.google.cloud.dataflow.worker.util.BatchGroupAlsoByWindowViaIteratorsFn.processElement(BatchGroupAlsoByWindowViaIteratorsFn.java:124)
        at com.google.cloud.dataflow.worker.util.BatchGroupAlsoByWindowViaIteratorsFn.processElement(BatchGroupAlsoByWindowViaIteratorsFn.java:53)
        at com.google.cloud.dataflow.worker.GroupAlsoByWindowFnRunner.invokeProcessElement(GroupAlsoByWindowFnRunner.java:114)
        at com.google.cloud.dataflow.worker.GroupAlsoByWindowFnRunner.processElement(GroupAlsoByWindowFnRunner.java:72)
        at com.google.cloud.dataflow.worker.GroupAlsoByWindowsParDoFn.processElement(GroupAlsoByWindowsParDoFn.java:113)
        at com.google.cloud.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:43)
        at com.google.cloud.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:48)
        at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:200)
        at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:158)
        at com.google.cloud.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:75)
        at com.google.cloud.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:383)
        at com.google.cloud.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:355)
        at com.google.cloud.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:286)
        at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.doWork(DataflowBatchWorkerHarness.java:134)
        at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:114)
        at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:101)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.beam.sdk.util.UserCodeException: java.lang.ArrayIndexOutOfBoundsException: 98
        at org.apache.beam.sdk.util.UserCodeException.wrap(UserCodeException.java:36)
        at org.apache.beam.sdk.io.gcp.spanner.SpannerIO$BatchFn$DoFnInvoker.invokeProcessElement(Unknown Source)
        at org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:177)
        at org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:138)
        at com.google.cloud.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:323)
        at com.google.cloud.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:43)
        at com.google.cloud.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:48)
        at com.google.cloud.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output(GroupAlsoByWindowsParDoFn.java:181)
        ... 21 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 98
        at org.apache.beam.sdk.io.gcp.spanner.MutationGroupEncoder.decodeMutation(MutationGroupEncoder.java:276)
        at org.apache.beam.sdk.io.gcp.spanner.MutationGroupEncoder.decode(MutationGroupEncoder.java:267)
        at org.apache.beam.sdk.io.gcp.spanner.SpannerIO$BatchFn.processElement(SpannerIO.java:944)
```

**Comment by mairbek** [comment]
@dsquier it could be related to https://github.com/apache/beam/pull/5722, could you please check?

**Comment by dsquier** [comment]
@mairbek Thanks, will do!

**Comment by O1O1O1O** [comment]
I experience similar (but not identical problems with 2.5.0) including:

```
java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: java.lang.RuntimeException: java.io.EOFException
at com.google.cloud.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output (GroupAlsoByWindowsParDoFn.java:183)
```

and

```
java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: java.lang.RuntimeException: java.io.IOException: varint too long
at com.google.cloud.dataflow.worker.GroupAlsoByWindowsParDoFn$1.output (GroupAlsoByWindowsParDoFn.java:183)
```

Both were fixed by cherry picking https://github.com/apache/beam/pull/5722 into Beam 2.5.0.  The fix is in 2.6.0-SNAPSHOT but that caused Dataflow jobs to die on GCP.

**Comment by O1O1O1O** [comment]
2.6.0-SNAPSHOT now has 2.6.0 RC1 and is working with Google Dataflow for me.

**Comment by mairbek** [comment]
cc @clifffrey

**Comment by dsquier** [comment]
Tested with the latest `0.5.7-SNAPSHOT` and still getting the error. Specific versions:

```
scioVersion = "0.5.7-SNAPSHOT"
beamVersion = "2.6.0"
defaultScalaVersion = "2.12.6"
```

NOTE: I had to add `beam-sdks-java-io-google-cloud-platform` to my `Dependencies.scala` to use the Spanner mutations object. Is this is the right one?

Here is the error:

```
com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException
Serialization trace:
columns (com.google.cloud.spanner.Mutation)
mutations (org.apache.beam.sdk.io.gcp.spanner.MutationGroup)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:543)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
	at com.spotify.scio.coders.KryoAtomicCoder$$anonfun$decode$1.apply(KryoAtomicCoder.scala:159)
	at com.spotify.scio.coders.KryoAtomicCoder$$anonfun$decode$1.apply(KryoAtomicCoder.scala:154)
	at com.spotify.scio.coders.KryoAtomicCoder$.withKryoState(KryoAtomicCoder.scala:260)
	at com.spotify.scio.coders.KryoAtomicCoder.decode(KryoAtomicCoder.scala:154)
	at org.apache.beam.sdk.coders.Coder.decode(Coder.java:159)
	at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.decode(WindowedValue.java:543)
	at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.decode(WindowedValue.java:480)
	at org.apache.beam.sdk.util.CoderUtils.decodeFromSafeStream(CoderUtils.java:115)
	at org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:98)
	at org.apache.beam.sdk.util.CoderUtils.decodeFromByteArray(CoderUtils.java:92)
	at com.google.cloud.dataflow.worker.AvroByteReader$AvroByteFileIterator.updateCurrent(AvroByteReader.java:125)
	at com.google.cloud.dataflow.worker.AvroByteReader$AvroByteFileIterator.start(AvroByteReader.java:106)
	at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation$SynchronizedReaderIterator.start(ReadOperation.java:360)
	at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:193)
	at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:158)
	at com.google.cloud.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:75)
	at com.google.cloud.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:393)
	at com.google.cloud.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:362)
	at com.google.cloud.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:290)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.doWork(DataflowBatchWorkerHarness.java:134)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:114)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:101)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:202)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:134)
	at com.esotericsoftware.kryo.serializers.CollectionSerializer.read(CollectionSerializer.java:40)
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
	... 34 more
```

**Comment by nevillelyh** [comment]
It's probably related to this: https://github.com/EsotericSoftware/kryo/issues/356
The easiest workaround is to add a custom serializer using the `KryoRegistrar` API. See https://github.com/spotify/scio/wiki/FAQ#how-do-i-use-custom-kryo-serializers

Can you give that a try?

**Comment by dsquier** [comment]
Will take a look, thanks @nevillelyh

**Comment by jbx** [comment]
This should be solved in more recent releases. Closing for now
